# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remote_db', '0003_auto_20160523_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ManyToManyField(related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
    ]
