# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_db', '0004_dashboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='db_connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='remote_db.DbConnection'),
            preserve_default=False,
        ),
    ]
