# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_db', '0006_auto_20160601_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='dbconnection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='widget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='remote_db.Dashboard'),
        ),
    ]
